---

- name: "Go-Lang | Removing GOROOT"
  file:
    path: "{{ GOROOT }}"
    state: absent
  failed_when: false

- name: "Go-Lang | Removing GOBOOTSTRAP"
  file:
    path: "{{ GOROOT_BOOTSTRAP }}"
    state: absent
  when:
   - GOROOT_BOOTSTRAP is defined
   - install_go_bootstrap|bool == true
  failed_when: false

- name: "Go-Lang | Define shell exports to cleanup"
  set_fact:
    shell_exports:
    - regex: "export GOROOT={{ GOROOT }}"
      lineinfile: "export GOROOT={{ GOROOT }}"
    - regex: "export GOPATH={{ GOPATH }}/bin"
      lineinfile: "export GOPATH={{ GOPATH }}/bin"
    - regex: "export PATH=$PATH:{{ GOPATH }}/bin"
      lineinfile: "export PATH=$PATH:{{ GOPATH }}/bin"
  when: shell_exports is undefined

- name: "Go-Lang | Ensure shell profiles are clean"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item[0] }}"
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].lineinfile }}"
    state: absent
  with_nested:
  - "{{ shell_profiles }}"
  - "{{ shell_exports_static }}"
  ignore_errors: yes
  when: shell_exports is defined
