---

- name: "Go-Lang | Define list of package directories"
  set_fact:
    go_package_locations:
    - "{{ GOPATH }}/bin"
    - "{{ GOPATH }}/pkg"
    - "{{ GOPATH }}/src"
  when: go_reget

- name: "Go-Lang | Remove installed workspace packages"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ go_package_locations }}"
  ignore_errors: yes
  when:
    - go_reget
    - go_package_locations is defined

- name: "Go-Lang | Run get commands with modules"
  command: "{{ GOROOT }}/bin/go get -u {{ item.url }}"
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
#    GO111MODULE: "{{ GO111MODULE }}"
    GO111MODULE: "'on'"
  with_items: "{{ go_get }}"
  changed_when: false
  when: item.modules

- name: "Go-Lang | Run get commands without modules"
  command: "{{ GOROOT }}/bin/go get -u {{ item.url }}"
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
  with_items: "{{ go_get }}"
  changed_when: false
  when: item.modules is not defined or not item.modules