---

- name: "Go-Lang | Define list of package directories"
  set_fact:
    go_package_locations:
    - "{{ GOPATH }}/bin"
    - "{{ GOPATH }}/pkg"
    - "{{ GOPATH }}/src"
  when: go_reget|bool == true

- name: "Go-Lang | Remove installed workspace packages"
  become: yes
  become_user: "root"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ go_package_locations }}"
  ignore_errors: yes
  when:
    - go_reget|bool == true
    - go_package_locations is defined

- name: "Go-Lang | Run get commands"
  shell: "{{ GOPATH }}/go get -u {{ item.url }}"
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
  with_items: "{{ go_get }}"
  changed_when: false

- name: "Go-Lang | Clone packages"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ GOPATH }}/src/{{ item.dest }}"
    version: "{{ item.version }}"
    clone: yes
    update: yes
  with_items: "{{ go_install }}"

- name: "Go-Lang | Install packages"
  shell: "{{ GOPATH }}/go install {{ item.dest }}/..."
  environment:
    GOROOT: "{{ GOROOT }}"
    GOPATH: "{{ GOPATH }}"
  with_items: "{{ go_get }}"