---

- name: "GoPM | Run get commands for static install"
  become: yes
  become_user: "root"
  shell: "{{ go_location }}/bin/go get -u {{ item.url }}"
  environment:
    GOPATH: "{{ go_location }}/bin"
    GOROOT: "{{ go_location }}"
  with_items: "{{ go_get }}"

- name: "GoPM | Link binaries"
  become: yes
  become_user: root
  file:
    src: "{{ go_location }}/bin/bin/{{ item.name }}"
    dest: "{{ go_location }}/bin/{{ item.name }}"
    state: link
    mode: 0755
    owner: "{{ fubarhouse_user }}"
    force: yes
  with_items: "{{ go_get }}"

- name: "GoPM | Install packages for static installs"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ go_location }}/modules/bin/gopm install {{ item }}"
  with_items: "{{ gopm_packages }}"
  when: '"github.com/gpmgo/gopm" in "{{ go_get }}"'