---

- name: "GoPM | Check folder permissions/state"
  become: yes
  become_user: "root"
  file:
    path: "{{ go_location }}/modules"
    state: directory
    mode: 0755
    owner: "{{ fubarhouse_user }}"
    recurse: yes

- name: "GoPM | Include tasks for static install"
  include: "gopm-static.yml"
  when: go_install_type == "static"

- name: "GoPM | Include tasks for source install"
  include: "gopm-source.yml"
  when: go_install_type == 'source'

- name: "GoPM | Include tasks for version-specific install"
  include: "gopm-version.yml"
  when: go_install_type == 'gvm'