---

- name: "Go-Lang | Include bootstrap tasks"
  include_tasks: install-bootstrap.yml
  when:
    (install_go_bootstrap|bool == true) and
    ((go_binary_bootstrap.stat.exists|bool == false) or
    (expected_go_version_output|string not in current_go_version.stdout|default('')) or
    (go_install_clean|bool == true)) and
    (GOROOT_BOOTSTRAP is defined)

- name: "Go-Lang | Include source build tasks"
  include_tasks: install-git.yml
  when:
    (build_go_from_source|bool == true) and
    ((expected_go_version_output|string not in current_go_version.stdout|default('')) or
    (go_install_clean|bool == true))

- name: "Go-Lang | Include distro install tasks"
  include_tasks: install-distro.yml
  when:
    (build_go_from_source|bool == false) and
    ((expected_go_version_output|string not in current_go_version.stdout|default('')) or
    (go_install_clean|bool == true))

- name: "Go-Lang | Ensure shell profiles are configured"
  lineinfile:
    dest: "{{ item[0] }}"
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].lineinfile }}"
    state: present
  with_nested:
  - "{{ golang_shell_profile }}"
  - "{{ shell_exports }}"
  when:
  - golang_shell_profile is defined

- name: "Go-Lang | Verify version"
  shell: "{{ GOROOT }}/bin/go version"
  environment:
    GOROOT: "{{ GOROOT }}"
    GOPATH: "{{ GOPATH }}"
  register: go_version_output
  failed_when: >
    (go_version_string not in go_version_output.stdout) and
    ("go version devel" not in go_version_output.stdout)
  changed_when: false

- name: "Go-Lang | Restart shell"
  shell: "{{ golang_shell_profile }}"
  failed_when: false
