---

- name: "GVM | Specify Debian dependencies"
  set_fact:
    gvm_dependencies:
#    - golang
    - curl
    - git
    - mercurial
    - make
    - binutils
    - bison
    - gcc
    - build-essential
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "GVM | Specify RedHat dependencies"
  set_fact:
    gvm_dependencies:
#    - golang
    - curl
    - git
    - make
    - bison
    - gcc
    - glibc-devel
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "GVM | Ensure dependencies are met"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ gvm_dependencies }}"
  when: gvm_dependencies is defined

- name: "GVM | Git"
  git:
    repo: https://github.com/moovweb/gvm.git
    dest: "{{ GVM_DEST }}"
    clone: yes
    update: yes
    force: yes
  failed_when: false

- name: "GVM | Define shell exports"
  set_fact:
    shell_exports:
    - regex: "export GO_ROOT={{ go_location }}"
      lineinfile: "export GO_ROOT={{ go_location }}"
    - regex: "export GOROOT={{ go_location }}"
      lineinfile: "export GOROOT={{ go_location }}"
    - regex: "export GOPATH={{ go_location }}/bin"
      lineinfile: "export GOPATH={{ go_location }}/bin"
    - regex: export PATH=\$PATH:\$GOROOT/bin
      lineinfile: export PATH=$PATH:$GOROOT/bin
    - regex: "{{ GVM_DEST }}/scripts/env/gvm"
      lineinfile: source "{{ GVM_DEST }}/scripts/env/gvm"
  when: shell_exports is undefined

- name: "GVM | Ensure shell profiles are available"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  file:
    path: "{{ fubarhouse_user_dir }}/{{ item }}"
    state: touch
  with_items: "{{ shell_profiles }}"
  failed_when: false
  when: shell_exports is defined

- name: "GVM | Ensure shell profiles are configured"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item[0] }}"
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].lineinfile }}"
    state: present
  with_nested:
  - "{{ shell_profiles }}"
  - "{{ shell_exports }}"
  ignore_errors: yes
  when: shell_exports is defined

- name: "GVM | Ensure directories are created"
  become: yes
  become_user: "root"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fubarhouse_user }}"
    mode: 0755
    recurse: yes
  with_items:
  - "{{ GVM_DEST }}"
  - "{{ GVM_DEST }}/archive"
  - "{{ GVM_DEST }}/logs"
  - "{{ GVM_DEST }}/environments"
  - "{{ GVM_DEST }}/pkgsets/system/global"
  - "{{ GVM_DEST }}/gos/system"

- name: "GVM | Touch GVM script"
  become: yes
  become_user: "root"
  file:
    path: "{{ GVM_DEST }}/scripts/gvm"
    state: touch
    mode: 0777
    owner: "{{ fubarhouse_user }}"

- name: "GVM | Configure GVM script"
  become: yes
  become_user: "root"
  template:
    src: gvm.j2
    dest: "{{ GVM_DEST }}/scripts/gvm"

  ignore_errors: yes

- name: "GVM | Copy environment files"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  template:
    src: "{{ item.file }}"
    dest: "{{ GVM_DEST }}/environments/{{ item.name }}"
  with_items:
  - name: system
    file: system.j2
  - name: default
    file: default.j2

- name: "GVM | Ensure backup URL points to valid URL"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  replace:
    dest: "{{ go_location }}/scripts/install"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
  - regexp: 'https://go.googlecode.com/files'
    replace: "{{ go_custom_mirror }}"
  - regexp: 'Trying https://go.googlecode.com'
    replace: "Trying {{ go_custom_mirror }}"

- name: "GVM | Ensure backup URL points to valid URL"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  replace:
    dest: "{{ go_location }}/scripts/install"
    regexp: 'https://go.googlecode.com/files/'
    replace: 'https://storage.googleapis.com/golang/go'

- name: "GVM | Get installed versions"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ GVM_DEST }}/bin/gvm list"
  environment:
    GVM_ROOT: "{{ go_location }}"
  register: all_go_versions
  failed_when: false

- name: "GVM | Include tasks for static install"
  include: "install-gvm-static.yml"
  when: go_install_type == 'static'

- name: "GVM | Include tasks for source install"
  include: "install-gvm-source.yml"
  when: go_install_type == 'source'

- name: "GVM | Include tasks for version-specific install"
  include: "install-gvm-version.yml"
  when: go_install_type == 'gvm'