---

- name: "Go-Lang | Clone distribution"
  git:
    repo: "https://github.com/golang/go.git"
    dest: "{{ GOROOT }}"
    version: "go{{ go_version }}"
    clone: yes
    update: no
    force: yes

- name: "Go-Lang | Build from source"
  shell: "cd {{ GOROOT }}/src && ./{{ go_build_script }}"
  environment:
    GOROOT: "{{ GOROOT }}"
    GOPATH: "{{ GOPATH }}"
    GOROOT_BOOTSTRAP: "{{ GOROOT_BOOTSTRAP }}"
