---
# main tasks file for fubarhouse-golang

- name: "Include tasks gathering system information"
  include: setup.yml

- name: "Include tasks to clean installation"
  include: cleanup.yml
  when: go_install_clean|bool == true

- name: "Include tasks for installation"
  include: install.yml
  when: (current_go_version is not defined) or
        (expected_go_version_output|string not in current_go_version.stdout|default(''))

- name: "Include tasks for Go Get"
  include: go-get.yml
  when: go_get.0 is defined

- name: "Include tasks for Go Install"
  include: go-install.yml
  when: go_install.0 is defined

- name: "Include tasks for setting Go permissions"
  include: perm.yml

- debug:
    msg: "{{ expected_go_version_output }}"

- debug:
    msg: "{{ current_go_version.stdout }}"