---
# main tasks file for fubarhouse-golang

- name: "Include tasks gathering system information"
  include: setup.yml

- name: "Include tasks to clean installation"
  include: cleanup.yml
  when: go_install_clean == true

- name: "Include tasks for installation"
  include: install.yml
  when:
    - current_go_version is undefined or "go version go{{ go_version }} {{ GOOS }}/{{ GOARCH }}" not in current_go_version.stdout
    - install_go_from_source == false

# - name: "Include tasks for installation from source"
#   include: install-source.yml
#   when: install_go_from_source == true

- name: "Include tasks for Go Get"
  include: go-get.yml
