---
# main tasks file for fubarhouse-golang

- name: "Include tasks gathering system information"
  include: setup.yml

- name: "Include tasks to clean installation"
  include: cleanup.yml
  when: go_install_clean|bool == true

- name: "Include tasks for installation"
  include: install.yml
  when: current_go_version is undefined or '"go version go{{ go_version }} {{ GOOS }}/{{ GOARCH }}" not in current_go_version.stdout'

- name: "Include tasks for Go Get"
  include: go-get.yml
