---
# tasks file for fubarhouse-golang

- name: "Include tasks for a clean installation"
  include: cleanup.yml
  when: go_install_clean == true

- name: "Include tasks for a static installation"
  include: install-static.yml
  when: go_install_type == "static"

- name: "Include tasks for a source install via GVM"
  include: install-gvm.yml
  when: go_install_type == "source"

- name: "Include tasks for a dynamic installation via GVM"
  include: install-gvm.yml
  when: go_install_type == "gvm"

- name: "Include tasks for GoPM packages"
  include: gopm.yml
  when: go_install_type == "gvm" or go_install_type == "source" or go_install_type == "static"

- name: "Reset Go permissions"
  file:
    dest: "{{ go_location }}"
    owner: "{{ fubarhouse_user }}"
    mode: 0775
    recurse: yes