---

# Define system-specific variables for fubarhouse.golang.

- name: "Go-Lang | Define GOROOT_BOOTSTRAP"
  set_fact:
    GOROOT_BOOTSTRAP: "{{ shell_home_dir.stdout }}/go1.4"
  when:
   - GOROOT_BOOTSTRAP is not defined
   - build_go_from_source|bool == true
   - shell_home_dir.stdout is defined

- name: "Go-Lang | Looking for compiled binary in GOROOT_BOOTSTRAP installation"
  stat:
    path: "{{ GOROOT_BOOTSTRAP }}/bin/go"
  register: go_binary_bootstrap
  failed_when: false
  when:
   - GOROOT_BOOTSTRAP is defined
   - build_go_from_source|bool == true

- name: "Go-Lang | Define GOARCH for 32-bit systems"
  set_fact:
    GOARCH: "386"
  when:
    - '"386" in ansible_architecture'
    - GOARCH is not defined

- name: "Go-Lang | Define GOARCH for 64-bit systems"
  set_fact:
    GOARCH: "amd64"
  when:
    - ansible_architecture == 'x86_64' or ansible_distribution == 'CentOS' or ansible_distribution == 'Debian' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Ubuntu'
    - GOARCH is not defined

- name: "Go-Lang | Define GOOS for Darwin systems"
  set_fact:
    GOOS: "darwin"
  when:
    - ansible_os_family == 'Darwin'
    - ansible_distribution == 'MacOSX'
    - GOOS is not defined

- name: "Go-Lang | Define GOOS for FreeBSD systems"
  set_fact:
    GOOS: "freebsd"
  when:
    - ansible_distribution == 'FreeBSD'
    - GOOS is not defined

- name: "Go-Lang | Define GOOS for linux systems"
  set_fact:
    GOOS: "linux"
  when:
    - ansible_architecture == 'x86_64' or ansible_distribution == 'CentOS' or ansible_distribution == 'Debian' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Ubuntu'
    - GOOS is not defined

- name: "Go-Lang | Define URL for distribution"
  set_fact:
    go_distribution_filename: "go{{ go_version }}.{{ GOOS }}-{{ GOARCH }}"
  when: build_go_from_source|bool == false

- name: "Go-Lang | Define URL for source"
  set_fact:
    go_distribution_filename: "go{{ go_version }}.src"
  when: build_go_from_source|bool == true

- name: "Go-Lang | Looking for existing installation"
  stat:
    path: "{{ GOROOT }}/bin/go"
  register: go_binary
  failed_when: false

- name: "Go-Lang | Define GOROOT"
  set_fact:
    GOROOT: "{{ GOROOT }}"
  when: GOROOT is defined

- name: "Go-Lang | Define GOPATH"
  set_fact:
    GOPATH: "{{ GOROOT }}/bin"
  when:
    - GOPATH is not defined
    - GOROOT is defined

- name: "Go-Lang | Getting version information"
  become: yes
  become_user: "root"
  shell: "{{ GOPATH }}/go version"
  environment:
    GOPATH: "{{ GOPATH }}"
    GOROOT: "{{ GOROOT }}"
  register: current_go_version
  changed_when: false
  when: go_binary.stat.exists|bool == true

- name: "Go-Lang | Define expected version output"
  set_fact:
    expected_go_version_output: "go version go{{ go_version }} {{ GOOS }}/{{ GOARCH }}"
  when: expected_go_version_output is not defined